In [1]:
import pandas as pd

In [2]:

#df = pd.read_csv (r'Path where the CSV file is stored\File name.csv')
   # print (df)

In [3]:
movies_data = pd.read_csv(r'C:\Users\91989\Downloads\IMDb movies-1.csv')

In [4]:
print(movies_data)

     imdb_title_id                        title               original_title  \
0        tt0000009                   Miss Jerry                   Miss Jerry   
1        tt0000574  The Story of the Kelly Gang  The Story of the Kelly Gang   
2        tt0001892               Den sorte drøm               Den sorte drøm   
3        tt0002101                    Cleopatra                    Cleopatra   
4        tt0002130                    L'Inferno                    L'Inferno   
...            ...                          ...                          ...   
9994     tt0052950                   Il viaggio                  The Journey   
9995     tt0052953            La giumenta verde              La jument verte   
9996     tt0052954               Fiori di carta              Kaagaz Ke Phool   
9997     tt0052957                    La chiave                         Kagi   
9998     tt0052961                         Kapò                         Kapò   

      year date_published              

In [5]:
movies_data.head()

imdb_title_id                        title               original_title  \
0     tt0000009                   Miss Jerry                   Miss Jerry   
1     tt0000574  The Story of the Kelly Gang  The Story of the Kelly Gang   
2     tt0001892               Den sorte drøm               Den sorte drøm   
3     tt0002101                    Cleopatra                    Cleopatra   
4     tt0002130                    L'Inferno                    L'Inferno   

   year date_published                      genre  duration           country  \
0  1894     1894-10-09                    Romance        45               USA   
1  1906     1906-12-26    Biography, Crime, Drama        70         Australia   
2  1911     1911-08-19                      Drama        53  Germany, Denmark   
3  1912     1912-11-13             Drama, History       100               USA   
4  1911     1911-03-06  Adventure, Drama, Fantasy        68             Italy   

  language                             director  ...  \
0     None                      Alexander Black  ...   
1     None                         Charles Tait  ...   
2      NaN                            Urban Gad  ...   
3  English                   Charles L. Gaskill  ...   
4  Italian  Francesco Bertolini, Adolfo Padovan  ...   

                                              actors  \
0  Blanche Bayliss, William Courtenay, Chauncey D...   
1  Elizabeth Tait, John Tait, Norman Campbell, Be...   
2  Asta Nielsen, Valdemar Psilander, Gunnar Helse...   
3  Helen Gardner, Pearl Sindelar, Miss Fielding, ...   
4  Salvatore Papa, Arturo Pirovano, Giuseppe de L...   

                                         description avg_vote votes   budget  \
0  The adventures of a female reporter in the 1890s.      5.9   154      NaN   
1  True story of notorious Australian outlaw Ned ...      6.1   589   $ 2250   
2  Two men of high rank are both wooing the beaut...      5.8   188      NaN   
3  The fabled queen of Egypt's affair with Roman ...      5.2   446  $ 45000   
4  Loosely adapted from Dante's Divine Comedy and...      7.0  2237      NaN   

   usa_gross_income worlwide_gross_income metascore reviews_from_users  \
0               NaN                   NaN       NaN                1.0   
1               NaN                   NaN       NaN                7.0   
2               NaN                   NaN       NaN                5.0   
3               NaN                   NaN       NaN               25.0   
4               NaN                   NaN       NaN               31.0   

   reviews_from_critics  
0                   2.0  
1                   7.0  
2                   2.0  
3                   3.0  
4                  14.0  

[5 rows x 22 columns]

In [6]:
features = ["original_title", "genre", "duration", "country", "director", "actors", "description", "avg_vote", "votes"]

movies_data["language"].fillna("xyz", inplace=True)
movies_data.drop(["imdb_title_id","original_title", "year", "language", "writer", "production_company", "budget", "usa_gross_income", "worlwide_gross_income", "metascore", "reviews_from_users", "reviews_from_critics"], axis=1)
# movies_data["language"].isnull().sum()

title date_published                      genre  \
0                      Miss Jerry     1894-10-09                    Romance   
1     The Story of the Kelly Gang     1906-12-26    Biography, Crime, Drama   
2                  Den sorte drøm     1911-08-19                      Drama   
3                       Cleopatra     1912-11-13             Drama, History   
4                       L'Inferno     1911-03-06  Adventure, Drama, Fantasy   
...                           ...            ...                        ...   
9994                   Il viaggio     1959-02-11        Drama, Romance, War   
9995            La giumenta verde     1959-10-29     Comedy, Drama, History   
9996               Fiori di carta     1959-01-02                    Romance   
9997                    La chiave     1959-06-23                      Drama   
9998                         Kapò     1960-09-29                 Drama, War   

      duration                    country  \
0           45                        USA   
1           70                  Australia   
2           53           Germany, Denmark   
3          100                        USA   
4           68                      Italy   
...        ...                        ...   
9994       126                        USA   
9995        90              France, Italy   
9996       148                      India   
9997        96                      Japan   
9998       117  Italy, France, Yugoslavia   

                                 director  \
0                         Alexander Black   
1                            Charles Tait   
2                               Urban Gad   
3                      Charles L. Gaskill   
4     Francesco Bertolini, Adolfo Padovan   
...                                   ...   
9994                       Anatole Litvak   
9995                   Claude Autant-Lara   
9996                            Guru Dutt   
9997                         Kon Ichikawa   
9998                     Gillo Pontecorvo   

                                                 actors  \
0     Blanche Bayliss, William Courtenay, Chauncey D...   
1     Elizabeth Tait, John Tait, Norman Campbell, Be...   
2     Asta Nielsen, Valdemar Psilander, Gunnar Helse...   
3     Helen Gardner, Pearl Sindelar, Miss Fielding, ...   
4     Salvatore Papa, Arturo Pirovano, Giuseppe de L...   
...                                                 ...   
9994  Deborah Kerr, Yul Brynner, Jason Robards, Robe...   
9995  Bourvil, Francis Blanche, Sandra Milo, Yves Ro...   
9996  Waheeda Rehman, Guru Dutt, Kumari Naaz, Johnny...   
9997  Machiko Kyô, Ganjirô Nakamura, Junko Kanô, Tat...   
9998  Susan Strasberg, Laurent Terzieff, Emmanuelle ...   

                                            description  avg_vote  votes  
0     The adventures of a female reporter in the 1890s.       5.9    154  
1     True story of notorious Australian outlaw Ned ...       6.1    589  
2     Two men of high rank are both wooing the beaut...       5.8    188  
3     The fabled queen of Egypt's affair with Roman ...       5.2    446  
4     Loosely adapted from Dante's Divine Comedy and...       7.0   2237  
...                                                 ...       ...    ...  
9994  A British woman trying to escape Hungary with ...       6.9   1398  
9995    A feud between families in 1870's rural France.       5.4    243  
9996  Suresh Sinha, a famous director, discovers sta...       8.0   1968  
9997  A man getting on in years sets out to find a w...       6.9    726  
9998  A young Jewish girl leads an escape attempt fr...       7.6   1903  

[9999 rows x 10 columns]

In [7]:
un = list(movies_data["genre"].unique())

In [8]:
unlist = []

for x in un:
  y = x.split()
  for i in y:
    if i.strip(',') in unlist:
      continue
    else:
      unlist.append(i.strip(','))

unlist

['Romance',
 'Biography',
 'Crime',
 'Drama',
 'History',
 'Adventure',
 'Fantasy',
 'War',
 'Mystery',
 'Horror',
 'Western',
 'Comedy',
 'Family',
 'Action',
 'Sci-Fi',
 'Thriller',
 'Sport',
 'Animation',
 'Musical',
 'Music',
 'Film-Noir']

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
from itertools import combinations
tf = TfidfVectorizer(analyzer=lambda s: (c for i in range(1,3)
                     for c in combinations(s.split('|'), r=i)))
tfidf_matrix = tf.fit_transform(movies_data['genre'])
tfidf_matrix.shape

(9999, 613)

In [12]:
from wordcloud import WordCloud

In [14]:
pd.DataFrame(tfidf_matrix.todense(), columns=tf.get_feature_names(),   index=movies_data.title).sample(5, axis=1).sample(10, axis=0)

(Comedy, Romance, Drama,)  (Crime, Comedy,)  \
title                                                                          
Piccoli detectives                                     0.0               0.0   
SOS Scotland Yard                                      0.0               0.0   
La morsa d'acciaio                                     0.0               0.0   
Bäxtiyar                                               0.0               0.0   
Dangers of the Canadian Mounted                        0.0               0.0   
La taverna dell'allegria                               0.0               0.0   
Il diamante fatale                                     0.0               0.0   
Volga, Volga...                                        0.0               0.0   
I tre furfanti                                         0.0               0.0   
Guerra tra i pianeti                                   0.0               0.0   

                                 (Adventure, Fantasy, Thriller,)  \
title                                                              
Piccoli detectives                                           0.0   
SOS Scotland Yard                                            0.0   
La morsa d'acciaio                                           0.0   
Bäxtiyar                                                     0.0   
Dangers of the Canadian Mounted                              0.0   
La taverna dell'allegria                                     0.0   
Il diamante fatale                                           0.0   
Volga, Volga...                                              0.0   
I tre furfanti                                               0.0   
Guerra tra i pianeti                                         0.0   

                                 (Crime, Mystery,)  (Drama, Sci-Fi,)  
title                                                                 
Piccoli detectives                             0.0               0.0  
SOS Scotland Yard                              0.0               0.0  
La morsa d'acciaio                             0.0               0.0  
Bäxtiyar                                       0.0               0.0  
Dangers of the Canadian Mounted                0.0               0.0  
La taverna dell'allegria                       0.0               0.0  
Il diamante fatale                             0.0               0.0  
Volga, Volga...                                0.0               0.0  
I tre furfanti                                 0.0               0.0  
Guerra tra i pianeti                           0.0               0.0

In [15]:
from sklearn.metrics.pairwise import linear_kernel
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [16]:
print(cosine_sim)

[[1. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [27]:
movies_data = movies_data.reset_index()
titles = movies_data['title']
indices = pd.Series(movies_data.index, index=movies_data['title'])

In [21]:
def movie_recommendations(gmov, M, k=15):
  gmovx = M.loc[:,i].to_numpy().argpartition(range(-1,-k,-1))
  closest = M.columns[gmovx[-1:-(k+2):-1]]
  closest = closest.drop(i, errors='ignore')
  return pd.DataFrame(closest).merge(items).head(k)


In [28]:
def get_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores]
    return titles.iloc[movie_indices]

In [23]:
def get_recommendations_dodo(title, cosine_sim=cosine_sim):
    idx = indices[title]
    similarity_scores = list(enumerate(cosine_sim[idx]))
    similarity_scores= sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    similarity_scores= sim_scores[1:11]
    # (a, b) where a is id of movie, b is similarity_scores
    movies_indices = [ind[0] for ind in similarity_scores]
    movies = movies_df["title"].iloc[movies_indices]
    return movies

In [29]:
get_recommendations('Dangers of the Canadian Mounted')

1090                The Galloping Ghost
1322                    Uragano express
1526                         Corruption
2186                    The Mystery Man
2191       Le nuove avventure di Tarzan
2210                    Paradise Canyon
2338                   Captain Calamity
2611               Behind the Headlines
2621                      Born Reckless
2664                    Escape by Night
2755                Artiglio di velluto
2930                 Il diamante fatale
2956                  La resa dei conti
2999                    Fuoco al mulino
3077                     Racket Busters
3081                    Red River Range
3094             Duello col pirata nero
3201                         Boy Slaves
3216         Code of the Secret Service
3224       Daredevils of the Red Circle
3281                      Acciaio umano
3336             Mandrake, the Magician
3394          Secret Service of the Air
3400               Servizio della morte
3439               Twelve Crowded Hours


In [31]:
get_recommendations('Piccoli detectives')

963           La banda dei fantasmi
1439              Tangled Destinies
1957               She Loves Me Not
2309         Adventure in Manhattan
2874               Per la sua donna
2995             He Couldn't Say No
3047              Midnight Intruder
3181                Ask a Policeman
3288        La casa delle fanciulle
3324                       La preda
3475             Angeli del peccato
3512          Charlie Chan a Panama
3678                        Raffles
3959           Murder by Invitation
4006          Una donna è scomparsa
4055             Avventura a Bombay
4416       The Chance of a Lifetime
4995                  Fashion Model
5266           Home, Sweet Homicide
5485    Il segreto di Mary Harrison
5566             Piccoli detectives
5854                   Holiday Camp
5976                 Shanghai Chest
6314                 The Sky Dragon
7574      Francis contro la camorra
0                        Miss Jerry
1       The Story of the Kelly Gang
2                    Den sor